// ─── Shipping Label Types ─────────────────────────────────────────
// Data structures for BizRavana-generated A5 shipping labels
// Used during auto waybill dispatch and reprint flows

// ─── Sender Info (from businesses table) ──────────────────────────
export interface SenderInfo {
  businessName: string;
  businessPhone: string;
  /** Full business address (for label header) */
  businessAddress: string;
  /** URL to business logo image */
  businessLogoUrl: string | null;
}

// ─── Receiver Info (from order snapshot) ──────────────────────────
export interface ReceiverInfo {
  customerName: string;
  address: string;
  /** Primary contact phone number */
  phone: string | null;
  /** WhatsApp number (fallback if phone is empty) */
  whatsapp: string | null;
  /** COD value = total - advance_paid */
  codAmount: number;
}

// ─── Handling Instruction Options ─────────────────────────────────
export type HandlingInstruction =
  | "fragile"
  | "keep_dry"
  | "this_side_up"
  | "glass"
  | "do_not_bend";

export const HANDLING_INSTRUCTION_LABELS: Record<HandlingInstruction, string> = {
  fragile: "FRAGILE",
  keep_dry: "KEEP DRY",
  this_side_up: "THIS SIDE UP",
  glass: "GLASS",
  do_not_bend: "DO NOT BEND",
};

// ─── Full Label Data ──────────────────────────────────────────────
export interface ShippingLabelData {
  /** The waybill ID returned by the courier API */
  waybillId: string;
  /** Sender information from business profile */
  sender: SenderInfo;
  /** Receiver information from order snapshot */
  receiver: ReceiverInfo;
  /** Order number for reference */
  orderNumber: string;
  /** Order ID for reprint lookups */
  orderId: string;
  /** Currency code (e.g. "LKR") for formatting COD value */
  currencyCode: string;
  /** Resolved contact number (prefers phone, falls back to WhatsApp) */
  contactNumber: string | null;
  /** Courier provider display name (e.g. "Royal Express") */
  courierName: string;
  /** Enabled handling instructions for this label */
  handlingInstructions: HandlingInstruction[];
  /** Optional note or remark for the shipment */
  optionalNote: string;
  /** Date to display on the label (ISO date string) */
  labelDate: string;
}

// ─── Validation Result ────────────────────────────────────────────
export interface LabelValidationResult {
  valid: boolean;
  missingFields: string[];
}

// ─── Label Generation Result ──────────────────────────────────────
export interface LabelGenerationResult {
  /** The generated PDF as a Blob */
  pdfBlob: Blob;
  /** The PDF as a data URL for preview */
  dataUrl: string;
  /** The waybill ID used */
  waybillId: string;
}

// ─── Combined Labels Generation Result ──────────────────────────
export interface CombinedLabelGenerationResult {
  /** The combined PDF as a Blob */
  pdfBlob: Blob;
  /** The combined PDF as a data URL for preview */
  dataUrl: string;
  /** Number of labels successfully generated */
  successCount: number;
  /** Number of labels that failed */
  failCount: number;
  /** Waybill IDs of successful labels */
  waybills: string[];
}

// ─── Courier Shipment Metadata (stored on orders table) ───────────
export interface CourierShipmentMetadata {
  /** The courier provider slug (e.g. "royal_express") */
  provider: string;
  /** The courier provider display label */
  providerLabel: string;
  /** The waybill ID generated by the courier */
  waybill: string;
  /** ISO timestamp of when the shipment was created */
  shippedAt: string;
  /** Any additional courier-specific response data */
  rawResponse?: Record<string, unknown>;
}

// ─── Phone Number Formatting ──────────────────────────────────────
export interface FormattedContact {
  /** The formatted phone number ready for display */
  display: string;
  /** Whether this is from WhatsApp (fallback) */
  isWhatsAppFallback: boolean;
}
